# 项目数据源
spring:
  datasource:
   master:
     username: root
     password: 123456
     url: jdbc:mysql://localhost:3306/shushangyun?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
     driver-class-name: com.mysql.cj.jdbc.Driver
   temp:
     username: root
     password: 123456
     url: jdbc:mysql://localhost:3306/shushangyun_temp?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
     driver-class-name: com.mysql.cj.jdbc.Driver

# 日志配置
logging:
  level:
    #mapper层 sql日志 DEBUG级别输出
    com.example.dyndatasource.mapper: debug
    com.baomidou.dynamic: debug


# mybatis-plus的配置内容
mybatis-plus:
  # 此处有坑 单模块加载也需要配置*(classpath 紧挨着的星) 解决自定义SQL无法执行
  mapper-locations: classpath*:mapper/*Mapper.xml
  typeAliasesPackage: com.example.dyndatasource





